//------------------------------------------------------------------------
// Copyright(c) 2023 Max And Me.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "VstGPT.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "VstGPT VST3 (64Bit)"
#else
#define stringFileDescription "VstGPT VST3"
#endif
#define stringCompanyName "Max And Me\0"
#define stringLegalCopyright "Copyright(c) 2023 Max And Me."
#define stringLegalTrademarks                                                  \
    "VST is a trademark of Steinberg Media Technologies GmbH"
